# strongSwan IPsec Configuration — RPi5 as N3IWUE
# ===================================================
# Berdasarkan dokumen MCUT R323 Lab:
# RPi5 IP     : 192.168.30.2
# Callbox IP  : 192.168.100.101

config setup
    charondebug="ike 2, knl 2, cfg 2, net 2, esp 2, dmn 2, mgr 2"
    uniqueids=no

conn %default
    keyexchange=ikev2
    ike=aes256-sha256-modp2048!
    esp=aes256-sha256!
    dpdaction=restart
    dpddelay=30s

conn aquaculture-n3iwf
    left=192.168.30.2           # IP RPi5 (MCUT-PI-5)
    leftid=001016100000207@nai.epc.mnc016.mcc001.3gppnetwork.org
    leftauth=eap-aka
    leftsourceip=%config

    right=192.168.100.101       # IP Amarisoft Callbox Mini
    rightid=%any
    rightauth=pubkey
    rightsubnet=0.0.0.0/0

    auto=start
    type=tunnel
    closeaction=restart
    dpdtimeout=60s
